name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 세팅 (JDK 17)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 캐시
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Lint 먼저 실행(리포트 생성)
      - name: Run Lint (debug)
        run: ./gradlew lintDebug --stacktrace

      # 실패 여부와 관계없이 리포트 업로드
      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/lint-results-debug.xml
            app/build/reports/lint-results-debug.sarif

      # 4. 빌드-빌드 시 Lint는 스킵(중복 방지). 엄격 모드 원하면 -x lint 제거
      - name: Build project
        run: ./gradlew assembleDebug --stacktrace -x lint

      # 5. 유닛 테스트 실행 (필요 시)
      - name: Run tests
        run: ./gradlew testDebugUnitTest

      # 6. 빌드 아티팩트 저장 (APK 확인용)
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk